# --- CONFIGURAÇÃO DO BANCO DE DADOS (RAILWAY) ---
# O formato deve ser jdbc:mysql://HOST:PORTA/DATABASE
spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:22374/railway
spring.datasource.username=root
spring.datasource.password=FEVImaQSGeGobEFxkSHrIcAwNTNxOvGw

# --- CONFIGURAÇÕES DO HIBERNATE/JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- CONFIGURAÇÃO DA IA (GEMINI) ---
gemini.api.key=AIzaSyDvfDZ6MkWSxfC-j7elKAP35lBAzWogkTY